### ISSUE TITLE
Implement col-sm-* for grid

### ISSUE THREAD

**Issue by TooManyGecs** [stuyam/bootstrap-email#61]
Hey, I was digging through the sass files for the grid section, and there does not seem to be the `col-sm-*` classes available in bootstrap email. The solution is pretty simple: create `col-sm-1` through `col-sm-12` in `grid.scss`, add them all to the `.no-gutter` block starting on line 55, then add the following code within the `@media screen and (max-width:600px)` block in `head.scss`:

```
  table.row {
    th.col-sm-1 {
      width: 8.333333% !important;
    }
    th.col-sm-2 {
      width: 16.666667% !important;
    }
    th.col-sm-3 {
      width: 25% !important;
    }
    th.col-sm-4 {
      width: 33.333333% !important;
    }
    th.col-sm-5 {
      width: 41.666667% !important;
    }
    th.col-sm-6 {
      width: 50% !important;
    }
    th.col-sm-7 {
      width: 58.333333% !important;
    }
    th.col-sm-8 {
      width: 66.666667% !important;
    }
    th.col-sm-9 {
      width: 75% !important;
    }
    th.col-sm-10 {
      width: 83.333333% !important;
    }
    th.col-sm-11 {
      width: 91.666667% !important;
    }
    th.col-sm-12 {
      width: 100% !important;
    }
  }
```

This feature is useful for the project I'm currently working on, and I'd to make a pull request if it will get reviewed.

**Comment by stuyam** [comment]
There are only two sizes in bootstrap email due to compatibility restrictions, small and large devices. It works like bootstrap where you specify the class for small and up (mobile first). So you could do `col-3` if you want a col-3 on all devices, and you could do `col-3 col-lg-6` to be a column of 3 on small and column of 6 on large. Or `col-lg-6` to do a column of full width on small and column of 6 on large.
